title: Einar Ingebrigtsens Playground
description: >- # this means to ignore newlines until "baseurl:"
  A journey in software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ingebrigtsen.blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: einari
github_username:  einari

# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
