title: Einar Ingebrigtsens Playground
description: >- # this means to ignore newlines until "baseurl:"
  A journey in software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ingebrigtsen.blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: einari
github_username:  einari

social:
  name: Einar Ingebrigtsen
  links:
    - https://twitter.com/einari
    - https://github.com/einari


# collections:
#   posts:
#     output: true
#     permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "_posts/**/*"
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title/

# Site settings
layout: post
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

# Build settings
theme: jekyll-theme-chirpy
theme_mode: dark
lang: en
